VAGRANTFILE_API_VERSION = "2"

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
        config.vm.provider "docker" do |docker|
            docker.image = "lborguetti/ubuntu-vagrant"
            docker.has_ssh = true
            docker.ports = ["80:8080"]
    end

end
