FROM java

MAINTAINER Luciano Antonio Borguetti Faustino <lucianoborguetti@gmail.com>

WORKDIR /opt

RUN curl http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/luna/SR2/eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz | tar xvz

CMD /opt/eclipse/eclipse
