FROM grafana/grafana:2.5.0
MAINTAINER Luciano A. Borguetti Faustino <lucianoborguetti@gmail.com>

# Copy prometheus datasource plugin
COPY datasources/prometheus /usr/share/grafana/public/app/plugins/datasource/prometheus
